/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HW_H_RPCGEN
#define _HW_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPC_CHAT 0x30000824
#define RPC_CHAT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HW 1
extern  char ** hw_1(void *, CLIENT *);
extern  char ** hw_1_svc(void *, struct svc_req *);
#define STS 2
extern  int * sts_1(char **, CLIENT *);
extern  int * sts_1_svc(char **, struct svc_req *);
#define GFS 3
extern  char ** gfs_1(void *, CLIENT *);
extern  char ** gfs_1_svc(void *, struct svc_req *);
extern int rpc_chat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HW 1
extern  char ** hw_1();
extern  char ** hw_1_svc();
#define STS 2
extern  int * sts_1();
extern  int * sts_1_svc();
#define GFS 3
extern  char ** gfs_1();
extern  char ** gfs_1_svc();
extern int rpc_chat_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HW_H_RPCGEN */
